### ISSUE TITLE
Add a LICENSE file to this repo

### ISSUE THREAD

**Issue by tamsky** [starkandwayne/codex#71]

**Comment by tamsky** [comment]
I was imagining a typical MIT/GPL code-oriented license.

Does the LICENSE added apply to everything in this repo?
If the GFDL does apply to everything in the repo, awesome!
If not, please explain what's not covered.

**Comment by 7hunderbird** [comment]
@tamsky most of the content of this repo is documentation, which is why the LICENSE is a [GNU Free Document License](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License) is being used.

With regard to the code in the repository in the `bin` and `terraform` folder.  We could look at using a different license for that specifically.  It would be open source as well, probably MIT.  I'll get confirmation on that and we'll touch base again.
