### ISSUE TITLE
cloudfoundry routing db information missing

### ISSUE THREAD

**Issue by ipolyzos** [starkandwayne/codex#99]
following codex guide, in the beta environment deployment I get into an error due to routingdb information missing i.e.

> - $.meta.cf.routingdb.host: What hostname/IP is the routingdb available at?
> - $.meta.cf.routingdb.pass: Specify the password of the routingdb user
> - $.meta.cf.routingdb.port: What port is the routingdb listening on?
> - $.meta.cf.routingdb.scheme: Specify the type of database the routingdb is (postgres, mysql)
> - $.meta.cf.routingdb.user: Specify the user to connect to the routingdb

even though [cf-deployment seems to have this information in template files](https://github.com/starkandwayne/cf-deployment/blob/master/global/properties.yml) 

 could you please advice ?

**Comment by geofffranks** [comment]
@xiujiao can you help with this? IIRC you were working with the routingdb earlier

**Comment by xiujiao** [comment]
@geofffranks what do you think we remove the routing do part in the global level? Since it is not used by any site level for now. I can also change it back to what it was before I changed , but even that other deployment like openstack which does not use Postgres from Postgres release as default database will fail since it is assuming host is from  the ip of posgres-z1

**Comment by geofffranks** [comment]
Sounds reasonable

**Comment by xiujiao** [comment]
@ipolyzos hi, please pull upstream from the `cf-deployment` repo and your problem should be resolved.

**Comment by ipolyzos** [comment]
thanks, i can confirm it works fine now
